// Copyright 2026 Edgar Frolenkov All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "UI/Navigation/Types/LunarNavigationTypes.h"
#include "LunarComboBoxSelectedVisual.generated.h"

class ULunarComboBox;

/** Blueprint-owned complete closed-face presentation generated by one Lunar ComboBox. */
UCLASS(Abstract, Blueprintable)
class LUNAR_API ULunarComboBoxSelectedVisual : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Returns the ComboBox that owns this closed-face visual. */
	UFUNCTION(BlueprintPure, Category = "Lunar|UI|ComboBox|Selected Visual")
	ULunarComboBox* GetOwningComboBox() const { return OwningComboBox; }

	/** Returns the currently committed option snapshot. */
	UFUNCTION(BlueprintPure, Category = "Lunar|UI|ComboBox|Selected Visual")
	FLunarComboBoxOption GetSelectedOption() const { return SelectedOption; }

	/** Returns true when the ComboBox currently has no committed option. */
	UFUNCTION(BlueprintPure, Category = "Lunar|UI|ComboBox|Selected Visual")
	bool IsSelectionEmpty() const { return bIsEmpty; }

	/** Returns the latest Lunar interaction state of the owning ComboBox. */
	UFUNCTION(BlueprintPure, Category = "Lunar|UI|ComboBox|Selected Visual")
	FLunarUIVisualState GetComboBoxVisualState() const { return VisualState; }

	/** ComboBox instance that generated this visual. */
	UPROPERTY(BlueprintReadOnly, Category = "Lunar|UI|ComboBox|Selected Visual")
	TObjectPtr<ULunarComboBox> OwningComboBox = nullptr;

	/** Currently committed option, or a default value while empty. */
	UPROPERTY(BlueprintReadOnly, Category = "Lunar|UI|ComboBox|Selected Visual")
	FLunarComboBoxOption SelectedOption;

	/** True when empty selection is currently presented. */
	UPROPERTY(BlueprintReadOnly, Category = "Lunar|UI|ComboBox|Selected Visual")
	bool bIsEmpty = true;

	/** Latest full visual state published by the owning ComboBox. */
	UPROPERTY(BlueprintReadOnly, Category = "Lunar|UI|ComboBox|Selected Visual")
	FLunarUIVisualState VisualState;

protected:
	/** Blueprint event emitted when the committed option or empty state changes. */
	UFUNCTION(BlueprintImplementableEvent, Category = "Lunar|UI|ComboBox|Selected Visual|Events", meta = (DisplayName = "On Combo Box Selected Option Changed"))
	void BP_OnSelectedOptionChanged(const FLunarComboBoxOption& PreviousOption, const FLunarComboBoxOption& NewOption, bool bNewIsEmpty);

	/** Blueprint event emitted when the owning ComboBox visual state changes. */
	UFUNCTION(BlueprintImplementableEvent, Category = "Lunar|UI|ComboBox|Selected Visual|Events", meta = (DisplayName = "On Combo Box Visual State Changed"))
	void BP_OnComboBoxVisualStateChanged(const FLunarUIVisualState& NewState);

private:
	/** Initializes this generated visual with one authoritative snapshot. */
	void InitializeFromComboBox(ULunarComboBox* ComboBox, const FLunarComboBoxOption& InitialOption, bool bInitiallyEmpty, const FLunarUIVisualState& InitialState);
	/** Applies a new committed option and publishes it when changed. */
	void ApplySelectedOption(const FLunarComboBoxOption& NewOption, bool bNewIsEmpty);
	/** Applies a new owner visual state and publishes it when changed. */
	void ApplyVisualState(const FLunarUIVisualState& NewState);

	/** Guards the initial option publication. */
	bool bHasPublishedOption = false;
	/** Guards the initial visual-state publication. */
	bool bHasPublishedVisualState = false;

	friend class ULunarComboBox;
};
